[font]
repo = "kimght/LimbusFonts"
# local path if repo is not set, else asset name in repo releases
replacement_map_path = "replacement_map.json"
font_path = "merged_font.ttf"

[reference]
repo = "LocalizeLimbusCompany/LocalizeLimbusCompany"
branch = "main"
path = "./EN"

[priority]
order = [
  "StoryData/*.json"
]

[keyword_shorthands]
# \[(?P<keyword_id>[^:\[]+):(?P<text>(?:\\[\[\]]|[^\]])*)\](?:\((?P<color>#[0-9a-fA-F]{6})\))?
regex = "\\[(?P<keyword_id>[^:\\]]+):`(?P<text>[^`]*)`\\](?:\\((?P<color>#[0-9a-fA-F]{6})\\))?"
apply_for = [
  "Skills*.json",
  "Passive*.json",
  "EGOgift_*.json",
  "PanicInfo*.json",
  "MentalCondition*.json",
  "BattleKeywords*.json",
  "Bufs*.json",
]

# no_link = [
#   "BattleKeywords*.json",
#   "Bufs*.json",
#   "PanicInfo*.json",
# ]

[xml_escape]
singular_keywords = [
  "sprite",
  "style",
  "align",
  "size"
]

[[font_rules."ShopUI.json"]]
font = "pretendard"
path = '$.dataList[*].content'

[[font_rules."ActionEvents*.json"]]
font = "mikodacs"
path = '$.dataList[*].options[*].message'

[[font_rules."PanicInfo*.json"]]
font = "mikodacs"
path = '$.dataList[*].panicName'

[[font_rules."MirrorDungeonTheme-1.json"]]
font = "mikodacs"
path = '$.dataList[*].name'

[[font_rules."TutorialMainUIText.json"]]
font = "pretendard"
path = '$.dataList[*].content'

[[font_rules."SeasonTitle.json"]]
font = "bebas"
path = '$.dataList[*].content'

[[font_rules."CouponUIText.json"]]
font = "pretendard"
path = '$.dataList[*].content'

[[font_rules."BattlePass_Mission.json"]]
font = "pretendard"
path = '$.dataList[*].content'

[[font_rules."BattlePass.json"]]
font = "mikodacs"
path = '$.dataList[*].content'

[[font_rules."BattlePass_Banner-a1c7.json"]]
font = "bebas"
path = '$.dataList[*].content'

[[font_rules."MainUIText_UPDATE_ON_0720.json"]]
font = "mikodacs"
path = '$.dataList[*].content'

[[font_rules."StageChapterText*.json"]]
font = "mikodacs"
path = '$.dataList[*].chaptertitle'

[[font_rules."StageChapterText*.json"]]
font = "bebas"
path = '$.dataList[*].chapter'

[[font_rules."StageChapterText*.json"]]
font = "bebas"
path = '$.dataList[*].company'

[[font_rules."StageChapterText*.json"]]
font = "bebas"
path = '$.dataList[*].area'

[[font_rules."StoryTheaterOther.json"]]
font = "mikodacs"
path = '$.dataList[*].title'

[[font_rules."StagePartText.json"]]
font = "mikodacs"
path = '$.dataList[*].parttitle'

[[font_rules."AttributeText.json"]]
font = "mikodacs"
path = '$.dataList[*].name'

[[font_rules."MainUIText.json"]]
font = "mikodacs"
path = '$.dataList[*].content'

[[font_rules."UserInfo_Friends.json"]]
font = "mikodacs"
path = '$.dataList[*].content'

[[font_rules."kr_settings-ui-donttranslate.json"]]
font = "pretendard"
path = '$.dataList[*].content'

[[font_rules."MirrorDungeonName.json"]]
font = "mikodacs"
path = '$.dataList[*].content'

[[font_rules."MirrorDungeonUI*.json"]]
font = "mikodacs"
path = '$.dataList[*].content'

[[font_rules."MirrorDungeonUI_5_InfinityFloor.json"]]
font = "pretendard"
path = '$.dataList[*].content'

[[font_rules."BattleUIText.json"]]
font = "mikodacs"
path = '$.dataList[*].content'

[[font_rules."RailwayDungeonUI.json"]]
font = "mikodacs"
path = '$.dataList[*].content'

[[font_rules."RailwayDungeonUI_2.json"]]
font = "pretendard"
path = '$.dataList[*].content'

[[font_rules."RailwayDungeonUI_4.json"]]
font = "pretendard"
path = '$.dataList[*].content'

[[font_rules."RailwayDungeonUI_5.json"]]
font = "pretendard"
path = '$.dataList[*].content'

[[font_rules."RailwayDungeon.json"]]
font = "mikodacs"
path = '$.dataList[*].name'

[[font_rules."RailwayDungeon.json"]]
font = "mikodacs"
path = '$.dataList[*].longName'

[[font_rules."StoryDungeonUI.json"]]
font = "pretendard"
path = '$.dataList[*].content'

[[font_rules."Announcer*.json"]]
font = "mikodacs"
path = '$.dataList.[*].name'

[[font_rules."Passive*.json"]]
font = "mikodacs"
path = '$.dataList.[*].name'

[[font_rules."BattleKeywords*.json"]]
font = "mikodacs"
path = '$.dataList.[*].name'

[[font_rules."Bufs*.json"]]
font = "mikodacs"
path = '$.dataList.[*].name'

[[font_rules."Characters.json"]]
font = "mikodacs"
path = '$.dataList.[*].name'

[[font_rules."EGOgift_*.json"]]
font = "mikodacs"
path = '$.dataList.[*].name'

[[font_rules."EgoGiftCategory.json"]]
font = "mikodacs"
path = '$.dataList.[*].name'

[[font_rules."Egos.json"]]
font = "mikodacs"
path = '$.dataList.[*].name'

[[font_rules."Items*.json"]]
font = "mikodacs"
path = '$.dataList.[*].name'

[[font_rules."Enemies*.json"]]
font = "mikodacs"
path = '$.dataList.[*].name'

[[font_rules."Enemies*.json"]]
font = "mikodacs"
path = '$.dataList.[*].desc'

[[font_rules."Skills*.json"]]
font = "mikodacs"
path = '$.dataList.[*].levelList.[*].name'

[[font_rules."Assist-a1c7p2.json"]]
font = "mikodacs"
path = '$.dataList[*].name'

[[font_rules."Skills*.json"]]
font = "mikodacs"
path = '$.dataList.[*].levelList.[*].abName'

[[font_rules."DungeonArea*.json"]]
font = "mikodacs"
path = '$.dataList.[*].content'

[[font_rules."DungeonNode*.json"]]
font = "mikodacs"
path = '$.dataList.[*].stageList.[*].title'

[[font_rules."RewardDungeonUI.json"]]
font = "mikodacs"
path = '$.dataList.[*].content'

[[font_rules."LoginUIText.json"]]
font = "mikodacs"
path = '$.dataList.[*].content'

[[font_rules."SuccessRate.json"]]
font = "mikodacs"
path = '$.dataList.[*].content'

[[font_rules."StageNode*.json"]]
font = "mikodacs"
path = '$.dataList.[*].title'

[[font_rules."StageNode*.json"]]
font = "mikodacs"
path = '$.dataList.[*].place'

[[font_rules."ScenarioModelCodes-AutoCreated.json"]]
font = "mikodacs"
path = "$.dataList.[*].name"

[[font_rules."ScenarioModelCodes-AutoCreated.json"]]
font = "mikodacs"
path = "$.dataList.[*].nickName"

[[font_rules."Personalities.json"]]
font = "mikodacs"
path = "$.dataList.[*].title"

[[font_rules."StoryData/*.json"]]
font = "mikodacs"
path = "$.dataList.[*].teller"

[[font_rules."StoryData/*.json"]]
font = "mikodacs"
path = "$.dataList.[*].title"

[[font_rules."StoryData/*.json"]]
font = "mikodacs"
path = "$.dataList.[*].place"

[[font_rules."BgmLyrics/*.json"]]
font = "mikodacs"
path = "$.dataList.[*].content"
