[font]
repo = "kimght/LimbusFonts"
# local path if repo is not set, else asset name in repo releases
replacement_map_path = "replacement_map.json"

[[font.include]]
path = "Context/Context.ttf"
filename = "Context.ttf"

[[font.include]]
path = "Title/Title.ttf"
filename = "Title.ttf"

[reference]
repo = "LocalizeLimbusCompany/LocalizeLimbusCompany"
branch = "main"
path = "./EN"

[priority]
order = [
  "StoryData/*.json"
]

[keyword_shorthands]
# \[(?P<keyword_id>[^:\[]+):(?P<text>(?:\\[\[\]]|[^\]])*)\](?:\((?P<color>#[0-9a-fA-F]{6})\))?
regex = "\\[(?P<keyword_id>[^:\\]]+):`(?P<text>[^`]*)`\\](?:\\((?P<color>#[0-9a-fA-F]{6})\\))?"
apply_for = [
  "Skills*.json",
  "Passive*.json",
  "EGOgift_*.json",
  "PanicInfo*.json",
  "MentalCondition*.json",
  "BattleKeywords*.json",
  "Bufs*.json",
]

# no_link = [
#   "BattleKeywords*.json",
#   "Bufs*.json",
#   "PanicInfo*.json",
# ]

[xml_escape]
singular_keywords = [
  "sprite",
  "style",
  "align",
  "size"
]
