[project]
name = "LimbusCompanyRuMTL"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "jsonpath-ng>=1.7.0",
    "loguru>=0.7.3",
    "msgspec>=0.19.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.4",
]
