name: Build Mod Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build Mod DLL
      run: dotnet build ./src/LimbusCompanyBusRus.sln -c ML_Cpp_net6_interop

    - name: Prepare Release
      run: |
        New-Item -ItemType Directory -Path "Release/Mod/LimbusCompanyRuMTL" -Force
        Copy-Item -Path Localize "Release/Mod/LimbusCompanyRuMTL" -Recurse
        Copy-Item -Path Release/LimbusCompanyBusRUS_BIE.dll "Release/Mod/LimbusCompanyRuMTL" 
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: LimbusCompanyRuMTL_${{ github.ref }}
        path: |
          Release/Mod
          
