name: Build Mod Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Версия'   

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
        lfs: true
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build Mod DLL
      run: ./build.ps1 ${{ github.event.inputs.version }}

    - name: Prepare Release
      run: |
        New-Item -ItemType Directory -Path "Release/ModData" -Force
        Copy-Item -Path Localize "Release/ModData" -Recurse
        Copy-Item -Path Release/LimbusCompanyBusRUS_BIE.dll "Release/ModData/LimbusCompanyBusRUS_BIE_${{ github.event.inputs.version }}.dll" 
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          Release/ModData

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
        
    needs: build

    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: LimbusCompanyRuMTL
      - run: zip -r LimbusCompanyRuMTL_v${{ github.event.inputs.version }}.zip LimbusCompanyRuMTL
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "LimbusCompanyRuMTL_v${{ github.event.inputs.version }}.zip"
          bodyFile: "CHANGELOG.md"
          tag: v${{ github.event.inputs.version }}
