name: Build and Release Localization

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. v1.0.0)'
        required: true
        default: 'v0.0.0'

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras

      - name: Build Localization
        run: uv run -m scripts.build

      - name: Make assets
        run: |
          cd ./dist/localize
          zip -r ../localize_files.zip .
          cd ../..

      - name: Make README.md
        run: |
          cat CHANGELOG.md > ./dist/README.md
          echo -e "\n\n---\n\n" >> ./dist/README.md
          cat ./data/readme/release_template.md >> ./dist/README.md

      - name: Add extra assets
        run: cp -r ./data/extra ./dist/extra

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body_path: CHANGELOG.md
          draft: true
          files: |
            dist/localize_files.zip
            dist/README.md
            dist/extra/*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
