name: Build Mod DLL

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Версия'   

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build Mod DLL
      run: ./build.ps1 ${{ github.event.inputs.version }}
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          Release/LimbusCompanyBusRUS_BIE.dll
