name: Update Submodules

on:
  workflow_dispatch:

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Sync Submodules
      run: |
        git submodule update --remote --merge

    - name: Check Difference
      run: |
        git diff --exit-code || echo "has_changes=true" >> $GITHUB_ENV
      
    - name: Create Pull Request
      if: success() && env.has_changes == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.REPO_PAT }}
        commit-message: "feat: update submodules"
        branch: submodules-automatic-update
        delete-branch: true
        title: 'Update submodules'
        labels: |
          automated pr
