name: Update Submodules

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: Sync Submodules
      run: git submodule update --remote
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.REPO_PAT }}
        commit-message: "feat: update submodules"
        branch: submodules-automatic-update
        delete-branch: true
        title: 'Update submodules'
        labels: |
          automated pr
